=== softWDog/xmlparase/src/main/java/com/gethin/xmlparser/book.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!--bookstore元素，包括多个book子元素 -->
<!ELEMENT bookstore (book)*>
<!--book元素，包括name,author,year,price子元素-->
<!ELEMENT book (name,author,year,price)>
<!--book元素，有一个属性名为id的属性，这个属性是必须的 -->
<!ATTLIST book id ID #REQUIRED>
<!--name元素，元素只包括文本 -->
<!ELEMENT name (#PCDATA)>
<!--author元素，元素只包括文本 -->
<!ELEMENT author (#PCDATA)>
<!--author元素，元素只包括文本 -->
<!ELEMENT year (#PCDATA)>
<!--price元素，元素只包括文本 -->
<!ELEMENT price (#PCDATA)>

=== softWDog/xmlparase/src/main/java/com/gethin/xmlparser/bookstore.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE bookstore SYSTEM "book.dtd">
<bookstore>  
    <book id="book1">  
        <name>Java 核心技术</name>  
        <author>Cornell </author>  
        <year>2014</year>  
        <price>89</price>  
    </book>  
    <book id="book2">  
        <name>深入浅出MyBatis</name>  
        <author>杨开振</author>  
        <year>2016</year>  
        <price>69</price>  
    </book>  
    <book id="book3">  
        <name>Java RESTful Web Service实战</name>  
        <author>韩陆</author>  
        <year>2016</year>  
        <price>59</price>
    </book>  
</bookstore>
